#!/usr/bin/env php
<?php

if (file_exists(__DIR__.'../../autoload.php')) {
    require __DIR__.'../../autoload.php';
} else {
    require __DIR__.'/vendor/autoload.php';
}

$app = new Symfony\Component\Console\Application('Unisys API Installer', '1.0.0');
$app->add(new Unite\UnisysInstaller\NewCommand);
$app->run();